theme: minima
title: MZaam
author: Myriam  
email: myriam@mzaam.com
description: > # this means to ignore newlines until "baseurl:"
  MZaam offers digital conversion and digital marketing services. We specialize in Shopify migration. We offer e-commerce and consulting. Located in Montreal, Canada..

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
